### PR TITLE
Add test for multiple root rotations

### PR DESCRIPTION
**Pull request by lbonn**
Not so pretty

### CODE REVIEW

**Comment by lbonn** [comment]
@patrickvacek ugliest thing is the `root` property to make the internal `test_simple` pass

**Comment by patrickvacek** [comment]
> ugliest thing is the `root` property to make the internal `test_simple` pass

Okay, yeah, I overlooked that because I didn't understand it. :) What is that actually doing?

**Comment by lbonn** [comment]
Not entirely sure why this test behaves differently than actual runs we do in aktualizr but it expects a `root` member in Step.

**Comment by patrickvacek** [comment]
> Not entirely sure why this test behaves differently than actual runs we do in aktualizr but it expects a `root` member in Step.

Huh. Well, feel free to merge if you're ready.

**Pull request merged**
