### PR TITLE
Replace obsolete pycrypto with pycryptodome

### PR DESCRIPTION
**Pull request by zabbal**
The dependencies were regenerated using "make update". The "make test" results
are the same as before, no external tests were performed.

The pycrypto functions were used in a single sign() method in metadata.py only
for RSA signature so it should be covered by pycryptodome compatibility API.

### CODE REVIEW

**Comment by patrickvacek** [comment]
Easiest way to test is to open a PR in aktualizr that bumps the version of tuf-test-vectors and let it run through CI. Or test locally.

**Comment by zabbal** [comment]
> bumps the version of tuf-test-vectors

Where do we specify it? The only place I've found is setup.py but so far it's been always 0.0.0

**Comment by patrickvacek** [comment]
> Where do we specify it?

In an aktualizr repo, `cd tests/tuf-test-vectors` and then `git checkout` this branch/commit.

**Comment by patrickvacek** [comment]
> But aktualizr's CI/CD always use latest master?

Nope, it's whatever is pinned by the git repo config. This just came up for https://github.com/advancedtelematic/tuf-test-vectors/pull/59 and https://github.com/advancedtelematic/aktualizr/pull/1409.

**Comment by zabbal** [comment]
Where can I look up this "git repo config"?
The submodule is configured in aktualizr/.gitmodules but it does not specify neither branch nor particular commit?

**Comment by lbonn** [comment]
`git submodule update --remote` is not really a command that is part of our workflow. Indeed, when you do that, you ignore the current version specified in aktualizr and just moves to latest upstream. You can also cd in `tests/tuf-test-vectors` and checkout whatever you want.

You can also see that git should report some uncommitted changes in `git status` after you moved HEAD in the submodule.

What matters is what you get after running `git submodule update --recursive`, which will set everything to their pinned version in the current commit. You can visualize when the submodule has been moved by running `git log --submodule=log -p tests/tuf-test-vectors`.

**Comment by zabbal** [comment]
Ok, tested aktualizr locally with this change: exactly the same results as before.
Shall go ahead and merge this?

**Comment by patrickvacek** [comment]
> Ok, tested aktualizr locally with this change: exactly the same results as before.

The typical workflow would be to make an aktualizr PR that demonstrates that it works in CI, but I doubt there's a problem, so sure, let's just merge it!

**Pull request merged**
