### PR TITLE
Test an update if metadata version is the same while their content have been changed

### PR DESCRIPTION
**Pull request by mike-sul**
Add a test that verify whether aktualizr can perform an update if
targets and corresponding snapshot and timestamp metadata are updated
while their version is the same.
This test is specifically dedicated for the recent fix to the imagerepo
functionality

### CODE REVIEW

**Review by pattivacek — COMMENTED** [review]
This looks great. I forget, though: did we also see the problem with the Snapshot version not incrementing in the Timestamp metadata?

You should just do an interactive rebase to get rid of the commit from my PR in the Uptane namespace. I would prefer to do further work over there, but since I still haven't had time to fix https://github.com/uptane/aktualizr/pull/65, it doesn't really matter. I'll just port this over once it's merged.

**Comment by mike-sul** [comment]
> You should just do an interactive rebase to get rid of the commit from my PR in the Uptane namespace

Done.

>I would prefer to do further work over there, but since I still haven't had time to fix https://github.com/uptane/aktualizr/pull/65, it doesn't really matter.

I updated this repo/namespace. Let me know if I need to do it for the uptane namespaced repo.

**Comment by mike-sul** [comment]
> did we also see the problem with the Snapshot version not incrementing in the Timestamp metadata?

No, we didn't.
Aktualizr  actually does NOT do the step 5 of the [timestamp metadata update](https://github.com/theupdateframework/specification/blob/master/tuf-spec.md#update-the-timestamp-role--update-timestamp).
Aktualizr, does the check 4 of the snapshot update stage, which implies checking if the versions match.

Had aktualizr implemented the step 5 then it wouldn't have been a problem because it allows the versions equality.

```
The version number of the snapshot metadata file in the trusted timestamp metadata file, if any, MUST be less than or equal to its version number in the new timestamp metadata file. If not, discard the new timestamp metadata file, abort the update cycle, and report the failure.
```

**Comment by pattivacek** [comment]
Ah right. So the Snapshot seems well-covered. Do we need to worry about the Targets content changing without the version incrementing?

**Comment by pattivacek** [comment]
> > Do we need to worry about the Targets content changing without the version incrementing?
> 
> Not sure. If the Targets content changes while the version is the same then they are fine since it doesn't contradict the spec, as well as their hashes match hashes specified in snapshot metadata.

Makes sense, but I don't think we have a test for that. If that's something you're relying on now, it should be covered.

For now, though, let's merge this!

**Review by pattivacek — APPROVED** [review]

**Pull request merged**
