### PR TITLE
Bump version requirements

### PR DESCRIPTION
**Pull request by zabbal**
Due to issue with werkzeug (needed by flask) it's recommended to bump version
requirements. It does not affect us directly so it's not high priority.

N. B: I'd like to have a 2nd opinion to make sure this won't break smth due to version incompatibility or alike.

### CODE REVIEW

**Comment by lbonn** [comment]
Looks like requirements.txt wasn't updated and that's what we actually use in aktualizr's test suite.

It works with:
```
pip-compile -U --output-file requirements-dev.txt requirements-dev.in requirements.in
```

And the tests still pass with the new versions on aktualizr's side.

**Comment by zabbal** [comment]
Indeed, but with your command I've got exactly the same results - only -dev file is updated.

**Comment by lbonn** [comment]
Ah yes, sorry that was the wrong command. The two need to be run actually:

    pip-compile -U --output-file requirements-dev.txt requirements-dev.in requirements.in

But it seems that it's actually enough to just run `make update`

**Comment by lbonn** [comment]
Ok actually, `make update` is missing the `-U` flag. To me it makes sense to add it there.

**Comment by zabbal** [comment]
Is there some case where we don't want to use --upgrade for either?

**Comment by lbonn** [comment]
For the first question, I would say no: they should be updated at the same time. Just that the update operation should be manual so that somebody can check that it works fine.

For the second point, Not sure what you mean, for me neither have the option in the Makefile and I would suggest applying this patch:

```
diff --git a/Makefile b/Makefile
index 0002b60..f6f139f 100644
--- a/Makefile
+++ b/Makefile
@@ -38,8 +38,8 @@ test: init-dev ## Run the test suite
 
 .PHONY: update
 update: ## Update the requirements and virtualenv
-	@pip-compile requirements.in --output-file requirements.txt && \
-		pip-compile requirements-dev.in requirements.in --output-file requirements-dev.txt && \
+	@pip-compile -U requirements.in --output-file requirements.txt && \
+		pip-compile -U requirements-dev.in requirements.in --output-file requirements-dev.txt && \
 		$(MAKE) init
 
 venv: ## Create the virtualenv
```

**Comment by zabbal** [comment]
Excellent idea - this can go on top of this. Would you like to make a separate PR or update this one?

**Comment by lbonn** [comment]
Ok it's there :)

**Pull request merged**
